services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
  
  appointment_service:
    build:
      context: ./appointment_service
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
      - NOTIFICATION_SERVICE_URL=http://notification_service:8004/notify/
    volumes:
      - ./appointment_service:/app
  
  chatbot_service:
    build:
      context: ./chatbot_service
    ports:
      - "8002:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
      - NOTIFICATION_SERVICE_URL=http://notification_service:8004/notify/
      - KNOWLEDGE_BASE_PATH=/app/knowledge_base_respiratory_diseases.markdown
    volumes:
      - ./chatbot_service:/app
      - ./knowledge_base_respiratory_diseases.markdown:/app/knowledge_base_respiratory_diseases.markdown
  
  doctor_service:
    build:
      context: ./doctor_service
    ports:
      - "8003:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./doctor_service:/app
  
  notification_service:
    build:
      context: ./notification_service
    ports:
      - "8004:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ./notification_service:/app
  
  patient_service:
    build:
      context: ./patient_service
    ports:
      - "8005:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./patient_service:/app

volumes:
  postgres_data:
