# Generated by Django 4.2.21 on 2025-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('query_text', models.TextField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, null=True)),
                ('predicted_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
